apiVersion: v1
kind: Service
metadata:
  name: test-image
  labels:
    app: test-image-1
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 8080
    targetPort: 80
  selector:
    app: test-image-1
    tier: frontend-1
