apiVersion: v1
kind: Service
metadata:
  name: test-image
  labels:
    app: test-image-1
spec:
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  - name: https
    port: 8081
    targetPort: 8081
  selector:
    app: test-image-1
    tier: frontend-1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-sample-deployment
  labels:
    app: test-image-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-image-1
  template:
    metadata:
      labels:
        app: test-image-1
    spec:
      containers:
      - name: test-image-1
        //image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        image: $imagename:$BUILD_NUMBER
        ports:
        - containerPort: 8081
